### ISSUE TITLE
Travis CI build badge link broken: update to travis-ci.com

### ISSUE THREAD

**Issue by sjvrijn** [ECOLE-ITN/NguyenSSCI2021#5]
## Issue
The build badge [![Actions Status](https://api.travis-ci.org/anh05/BO4ML.svg?branch=master)](http://travis-ci.org/anh05/BO4ML) is showing 'unknown', and the link results in an error message on travis-ci.org:
> We couldn't display the repository
> anh05/BO4ML

A banner at the top of that page states:
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on."

However, simply changing `.org` to `.com` gives the same badge [![Actions Status](https://api.travis-ci.com/anh05/BO4ML.svg?branch=master)](http://travis-ci.com/anh05/BO4ML) and a 404 error:
> 404
> Oops, seems like you’ve came across the wrong job site builder, try again!

**Comment by anh05** [comment]
the travis-ci has been replaced by a zenodo DOI
